backtest:
  benchmark_code: 000300.SH
  commission: 0.0005
  cost_buffer: 0.003
  default_cash: 100000
  default_end: '20251231'
  default_start: '20210101'
  default_strategy: ETFEpoLowCorrCombo
  default_ts_code: 000001.SZ
  slippage_perc: 0.002
  target_percent: 0.98
data:
  cache_dir: ./data_cache
  cache_expiry_days: 7
  token: xx
strategies:
  etf_epo_lowcorr_combo:
    commission: 0.0002
    cost_buffer: 0.003
    etf_pool:
    - 159985.XSHE
    - 518800.XSHG
    - 513000.XSHG
    - 513100.XSHG
    - 513030.XSHG
    - 159930.XSHE
    - 159981.XSHE
    - 159980.XSHE
    - 510880.XSHG
    - 510230.XSHG
    lambda_: 10.0
    lookback: 250
    min_history: 200
    shrink_w: 0.6
    slippage_perc: 0.002
    target_percent: 0.98
visualization:
  enable_charts: true
  output_dir: ./results
