backtest:
  benchmark_code: 000300.SH
  commission: 0.0005
  cost_buffer: 0.003
  default_cash: 100000
  default_end: '20240501'
  default_start: '20180101'
  default_strategy: ETFCoreRotationStoploss
  default_ts_code: 000001.SZ
  slippage_perc: 0.002
  target_percent: 0.98
data:
  cache_dir: ./data_cache
  cache_expiry_days: 7
  token: xx
strategies:
  etf_core_rotation_stoploss:
    commission: 0.0002
    cost_buffer: 0.003
    etf_pool:
    - 518880.XSHG
    - 513100.XSHG
    - 159915.XSHE
    - 510180.XSHG
    history_window: 100
    hold_drop_threshold: 0.96
    m_days: 25
    slippage_perc: 0.0
    target_percent: 0.98
visualization:
  enable_charts: true
  output_dir: ./results
