data:
  token: "xx"

backtest:
  default_strategy: "ETFSafeDogRotation"
  default_cash: 100000
  default_start: "20210101"
  default_end: "20251231"
  benchmark_code: "000300.SH"

strategies:
  etf_safe_dog_rotation:
    commission: 0.0002
    slippage_perc: 0.001
    target_percent: 0.98
    cost_buffer: 0.003
    etf_pool:
      - "518880.XSHG"
      - "513100.XSHG"
      - "159915.XSHE"
      - "510180.XSHG"
    m_days: 25
    top_n: 1
    score_min: 0.0
    score_max: 5.0

visualization:
  output_dir: "./results"
  enable_charts: true
